services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-end/.env

  react:
    container_name: react
    build: ./front-end
    volumes:
      - react_volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - react_volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react_volume:
